-- Give the Sherlock sample world real chapter prose (was ~1-line synopses).
-- Original narration of the public-domain characters/plots — not the source
-- text — with the cast named so mention-highlighting and word counts read real.
-- One function is the single source of truth; the guest-seed wrapper calls it
-- for every new guest, and we backfill existing sample worlds below.
--
-- Guards: only fills a chapter whose body is still short (< 260 chars, i.e. an
-- untouched synopsis) and not a "planned" beat — so nobody's real writing or the
-- two deliberately-planned chapters (8, 18) are ever clobbered.

create or replace function _apply_sample_prose(p_world uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
begin
  update chapters c set body = m.body
  from (values
    (1, $p$Home from the war with a wound that aches when the weather turns, Watson drifts through London on an army pension and no purpose. A chance word from an old dresser at the hospital leads him to a tall, thin young man bent over a laboratory bench, testing a reagent that will, he says, at last let us tell human blood from any other. The man is Sherlock Holmes, and he is looking for someone to share rooms he cannot afford alone. Within the hour the two of them have agreed to take the first floor at 221B Baker Street, and Watson has begun a habit he will never quite break — watching Holmes, and wondering exactly what it is that he does.$p$),
    (2, $p$Watson finds his new companion impossible to file away. Holmes knows nothing of the solar system and everything of soils, tobacco ash, and the hundred kinds of mud a London street can leave on a boot. When Watson protests that no one could read a stranger's history from a glance, Holmes reads him — the tan of a fever climate, the stiff arm, the military bearing — and hands his own trade back to him: Afghanistan, in a sentence. He calls it the science of deduction, and insists it is as exact as arithmetic once you have troubled to learn the alphabet. Watson, half offended and wholly fascinated, begins to keep notes. He does not yet know he is writing the first pages of a long record.$p$),
    (3, $p$A note from Scotland Yard breaks the quiet of Baker Street. In an empty house off the Brixton Road a man lies dead — Enoch Drebber, without a wound on him, his face fixed in something between terror and hate. On the wall, scrawled in blood that is not his own, is a single word: RACHE. Inspector Lestrade reads it as an unfinished woman's name; Gregson has his own theory and guards it jealously. Holmes says almost nothing to either of them. He measures the room, tastes the air, studies the ash and the wheel-ruts in the clay outside, and leaves with the private, delighted look of a man who has already seen the shape of the whole thing while the professionals argue over a word.$p$),
    (4, $p$The nearest thing to a witness is the constable who found the body, and it takes Holmes to get anything useful out of him. John Rance had passed a drunk man swaying against the railings that night and thought nothing of it — never guessing, as Holmes gently makes him see, that he had held the murderer by the sleeve and let him go. For the rest, Holmes turns to his own irregular force: the ragged Baker Street children who go everywhere and are noticed nowhere. He sets them combing the cab-ranks of London for one particular four-wheeler and one particular driver, a shilling apiece and more for the one who finds it. Watson watches the net go out and cannot yet see what it means to catch.$p$),
    (5, $p$A plain gold wedding ring, dropped at the scene, becomes Holmes's bait. He places an advertisement claiming the ring has been found and waits at Baker Street to see who will come to reclaim it. Someone does — but it is a wizened old woman, all shawls and tears, with a story about her daughter that is a little too ready. Holmes hears her out, hands over a duplicate ring, and the moment she is gone slips into the street behind her. She gives him the neat, athletic slip of someone half her apparent age. He returns wry and unbothered; the trick has failed, but it has told him something all the same — that the man he wants is clever, and well served, and reading the papers as closely as Holmes is reading him.$p$),
    (6, $p$Gregson arrives at Baker Street flushed with triumph: he has made an arrest, and a tidy one. A young man who called at the dead man's lodging, a jealous quarrel, a plain motive — the case, he announces, is closed. Holmes lets him tell it all, asks two or three quiet questions, and by the answers alone dismantles the whole confident edifice without ever leaving his chair. The arrested man is no more the killer than Gregson is; the inspector has taken the easiest face in reach and called it a solution. Lestrade, off on a rival scent of his own, is faring no better. Between the two of them the Yard is very busy and entirely wrong, and Holmes, watching them work, seems almost sorry to have to be right.$p$),
    (7, $p$When Holmes finally moves, it is all at once. The Irregulars run the cab to ground; Holmes has the driver summoned to Baker Street on a pretext, and as the man stoops to a piece of luggage the handcuffs close on his wrists. This is the murderer — a cabman named Jefferson Hope, who has carried his victim through London in his own four-wheeler and offered him a fatal choice of two pills, one harmless and one not. Holmes lays the chain of it out for the astonished detectives: the wheel-ruts, the ash, the flush of the dead face, the ring that was never a robber's prize but a lover's relic. What looked like madness on a wall becomes, in his telling, the last move in a long and patient revenge.$p$),
    (9, $p$With Hope in custody the London threads draw together. The ring, the advertisement, the false old woman, the poison chosen so that chance alone would decide which man died — each piece that baffled the Yard settles into place. Holmes explains to Watson how little of it was guesswork and how much was simply refusing to look away from small things: the depth of a footprint, the length of a stride, the particular red of a clay. Hope himself is oddly at peace, a man who has spent twenty years walking toward one act and, having done it, has nowhere left to walk. Watson, listening, begins to feel the pull of the older story behind the London one — a wrong done far away and long ago, now come to its reckoning on a wet English street.$p$),
    (10, $p$Jefferson Hope tells the rest himself, and it is a confession more than a defence. Across years and an ocean he had hunted the two men who ruined the woman he loved, and one by one he had run them down. His heart, he knows, will finish the work the law would have; he asks only to be believed. When it is over, it is Gregson and Lestrade whose names reach the newspapers, their rivalry papered into a single official triumph, while the man who actually untangled it goes unmentioned. Holmes only laughs — the work was its own reward, and the credit was never the point. Watson thinks otherwise. Someone, he decides, ought to set down what really happened at Baker Street, and he takes up his pen to do it.$p$),
    (11, $p$A masked man calls at Baker Street by night and is soon unmasked, by Holmes, as a king. The royal difficulty is a photograph — proof of an old attachment to Irene Adler, a singer with wit enough to keep it and use it. Holmes takes the case as a puzzle of retrieval and lays his usual clever siege: a disguise, a staged accident, a cry of fire to make her betray the hiding place. It works exactly as designed, and it is not enough. Adler has read the game a step ahead, watched him leave, and gone — taking the photograph and leaving only a letter and a portrait of herself. Holmes, beaten cleanly for once, asks the king for that portrait as his fee, and keeps it. To him she remains, always, the woman.$p$),
    (12, $p$A pawnbroker named Wilson brings Holmes an absurdity: a society that pays red-headed men a comfortable wage to copy out the encyclopaedia, and that has now, without warning, dissolved. Watson expects nonsense; Holmes hears the click of something being kept out of the way. The whole ridiculous league, he sees, existed to lure one man from his shop for regular, predictable hours — and the only thing worth that trouble sits underground, where an accomplice has been digging a tunnel from the pawnbroker's cellar toward the vault of a nearby bank. Holmes lays a quiet trap in the dark of the vault and waits. When the flagstones lift and a hand comes through, the elaborate comedy of red hair ends in a very ordinary pair of handcuffs.$p$),
    (13, $p$In the west country a young man stands all but convicted of his father's murder — seen quarrelling with him, found beside the body, silent about what passed between them. Lestrade thinks it plain. Holmes, walking the ground the police have trampled, reads a different account in the reeds and the soft earth: a second man, taller, left-handed, a smoker of a particular cigar, who came and went unseen. The dead man's last broken word, taken for a curse, points instead to an old wrong carried home from the Australian goldfields. The killer is a respectable neighbour with a buried past, and a secret he would kill twice to keep. Holmes spares the dying man the dock and the son the rope, and lets a private confession do what a public trial could only have bungled.$p$),
    (14, $p$A frightened young man comes to Baker Street with an inheritance he never wanted: a letter marked only with five dried orange seeds, and a family history of the same envelope arriving before a sudden death. His uncle received it and died; his father received it and died; now it has come to him. Holmes traces the seeds and the initials to a vengeful society reaching across the Atlantic, punishing an old betrayal down the generations. For once his reasoning outruns his reach — before the protection he arranges can take hold, the sea gives up news that the young man, too, is dead. Holmes takes it hard, and sets himself to answer the murderers in their own coin; but the ocean that carried their threat swallows them first, and the account is closed by weather rather than by law.$p$),
    (15, $p$A respectable gentleman vanishes in a bad quarter of London, last glimpsed at an upstairs window of an opium den; in the room where he was seen, the police find only a hideous, twisted-lipped beggar and the missing man's coat, its pockets heavy with coins. Mrs St Clair is certain her husband lives; the evidence says he was murdered. Holmes sits up the whole night over the problem, and it is scrubbing that solves it — for the beggar's ruined face washes clean away. The vanished gentleman and the practised beggar are one and the same, a man who discovered that mock misery on the pavement paid better than honest work, and could not bear his family to learn how their comforts were earned. There is no crime here in the end, only a shabby secret and a great deal of shame.$p$),
    (16, $p$A young woman comes to Baker Street grey with fear. Her sister died two years past in a locked room, with a last cry about a speckled band and no mark on her to explain it; now she has been moved into that same room, and in the night she hears the same low whistle. Holmes and Watson go down to the crumbling estate and its violent master, a doctor with a temper, a menagerie, and a heavy financial reason to want his stepdaughters dead before they marry. In the dark they keep watch over the fatal room, and when the whistle comes and something moves along the dummy bell-rope, Holmes strikes at it savagely. The thing recoils — back down its channel to the man who sent it, and who dies by his own instrument before the night is out.$p$),
    (17, $p$For the first time Watson sees Holmes afraid — not of a man, but of a mind. Professor Moriarty sits at the centre of half the crime in London like a spider unseen at the middle of its web, and he has felt Holmes's hand closing on the threads. The two of them meet once, coldly, each promising the other's destruction. Holmes flees to the Continent to let the police spring their trap in London; Moriarty follows, shadowing them across Europe. It ends in Switzerland, above the roar of the Reichenbach Falls, where Watson is drawn away by a false message and returns to find only two sets of footprints going to the edge of the chasm and none coming back. The world is told that Sherlock Holmes is dead, and Watson, grieving, believes it.$p$)
  ) as m(ord, body)
  where c.world_id = p_world
    and c.manuscript_order = m.ord
    and c.planned = false
    and length(c.body) < 260;
end
$fn$;

revoke all on function _apply_sample_prose(uuid) from public;

-- New guests get the full prose: the public seed wrapper now fills it in.
create or replace function seed_sample_world()
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare uid uuid := auth.uid(); w uuid;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  w := _seed_sample_world(uid);
  perform _apply_sample_prose(w);
  return w;
end $$;

revoke all on function seed_sample_world() from public;
grant execute on function seed_sample_world() to authenticated;

-- Backfill every existing sample world (all current guest copies).
select _apply_sample_prose(id) from worlds where is_sample and deleted_at is null;
